# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
  - osx

julia:
  - 1.1

script:
  - julia -e 'using Pkg; pkg"dev PackageCompiler PyCall"'
  - julia -e 'using PackageCompiler; push!(Base.LOAD_PATH, normpath(ENV["HOME"], ".julia/dev/PyCall")); PackageCompiler.compile_incremental(:PyCall)'
  - if [[ "$TRAVIS_OS_NAME" == linux   ]]; then  time julia -J "$HOME/.julia/dev/PackageCompiler/sysimg/sys.so"    -e 'using PyCall'  ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx     ]]; then  time julia -J "$HOME/julia/lib/julia/sys.dylib" -e 'using PyCall'  ; fi
  - time julia -e 'using PyCall'
