# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
#  - osx
#  - windows

julia:
  - 1.1
#  - 1.3

script:
  - julia -e 'using Pkg; pkg"add PackageCompiler"; pkg"dev PyCall"; pkg"instantiate"'
  - julia -e 'using PackageCompiler; PackageCompiler.compile_incremental(:PyCall)'
  - time julia -J $HOME/.julia/PackageCompiler/sysimg/sys.dylib -e 'using PyCall'
  - time julia -J $HOME/.julia/PackageCompiler/sysimg/sys.dylib -e 'using PyCall'
  - time julia -e 'using PyCall'
  - time julia -e 'using PyCall'
#  - julia -e 'using PackageCompiler; PackageCompiler.compile_incremental((:PyCall)'
#  - time julia -J $HOME/.julia/PackageCompiler/sysimg/sys.dylib -e 'using PyCall'
#  - time julia -e 'using PyCall'
